"""Builds game/content/spanish/vocabulary.json: B1 vocabulary, Mexican Spanish first.
Run from the repository root: python3 tools/make_vocabulary.py"""
import json
T = {}
def add(theme, word, clue, example, alt=None, note=""):
    T.setdefault(theme, []).append({"word": word, "clue": clue, "example": example, "alt": alt or [], "note": note})
C = "cuerpo"
add(C,"el codo","Articulación en medio del brazo; se dobla para comer.","Me pegué en el codo con la puerta.")
add(C,"la rodilla","Articulación en medio de la pierna.","Se raspó la rodilla al caer del caballo.")
add(C,"el tobillo","Une la pierna con el pie.","Se torció el tobillo en el camino de piedras.")
add(C,"la muñeca","Une la mano con el brazo; ahí se lleva el reloj.","Lleva una pulsera en la muñeca.")
add(C,"el hombro","Parte donde el brazo se une al cuerpo; ahí se carga una mochila.","Cargaba el costal sobre el hombro.")
add(C,"la ceja","Línea de pelo encima del ojo.","Levantó una ceja, sorprendido.")
add(C,"la pestaña","Pelo pequeño en el borde del párpado.","Tenía una pestaña en el ojo.")
add(C,"la mejilla","Parte de la cara a cada lado de la nariz.","Le dio un beso en la mejilla.")
add(C,"la barbilla","Parte de la cara debajo de la boca.","Se apoyó la mano en la barbilla para pensar.")
add(C,"el cuello","Une la cabeza con el cuerpo.","Llevaba una bufanda alrededor del cuello.")
add(C,"la espalda","Parte de atrás del cuerpo, entre los hombros y la cintura.","Me duele la espalda de tanto cargar libros.")
add(C,"el pecho","Parte de delante del cuerpo, entre el cuello y el estómago.","Sintió un dolor en el pecho.")
add(C,"la uña","Parte dura al final de cada dedo.","Se mordía las uñas cuando estaba nervioso.")
add(C,"el talón","Parte de atrás del pie.","El zapato nuevo le lastimaba el talón.")
add(C,"la cadera","Parte del cuerpo entre la cintura y las piernas.","Se puso las manos en la cadera.")
add(C,"el pulgar","El dedo más grueso de la mano.","Levantó el pulgar para decir que todo estaba bien.")
add(C,"la frente","Parte de la cara encima de los ojos.","Tenía la frente caliente por la fiebre.")
add(C,"los pulmones","Órganos con los que respiramos.","El humo de la mina daña los pulmones.")
add(C,"el hígado","Órgano grande que limpia la sangre; le hace daño el alcohol.","El médico le revisó el hígado.")
add(C,"la garganta","Parte interior del cuello por donde pasa la comida.","Me duele la garganta; no puedo hablar.")
R = "ropa"
add(R,"la playera","Prenda de algodón de manga corta, sin botones.","Se puso una playera blanca.",["la camiseta"],"En México se dice «playera»; en España, «camiseta».")
add(R,"la chamarra","Prenda gruesa que se lleva encima para el frío.","Llévate la chamarra, va a hacer frío.",["la chaqueta"],"En México: «chamarra»; en España: «chaqueta» o «cazadora».")
add(R,"los aretes","Joyas que se llevan en las orejas.","Le regalaron unos aretes de plata.",["los pendientes"],"En México: «aretes»; en España: «pendientes».")
add(R,"las chanclas","Calzado abierto y ligero para la casa o la playa.","Andaba en chanclas por la casa.")
add(R,"los tenis","Zapatos deportivos.","Me compré unos tenis para correr.",["las zapatillas"],"En México: «tenis»; en España: «zapatillas».")
add(R,"el cinturón","Tira de cuero que sujeta el pantalón.","Se ajustó el cinturón antes de salir.")
add(R,"la bufanda","Prenda larga que protege el cuello del frío.","Se enrolló la bufanda dos veces.")
add(R,"los guantes","Prendas para cubrir las manos.","Usa guantes para trabajar en el jardín.")
add(R,"la gorra","Prenda para la cabeza con visera delante.","Se quitó la gorra al entrar.")
add(R,"el rebozo","Manta larga mexicana que las mujeres llevan sobre los hombros.","Su abuela llevaba un rebozo azul.")
add(R,"los huaraches","Sandalias mexicanas de cuero tejido.","Compró unos huaraches en el mercado.")
add(R,"la bolsa","Objeto para llevar cosas personales, normalmente de una mujer.","Guardó la cartera en la bolsa.",["el bolso"],"En México: «bolsa»; en España: «bolso».")
add(R,"los lentes","Dos cristales que ayudan a ver mejor.","No veo nada sin mis lentes.",["las gafas","los anteojos"],"En México: «lentes»; en España: «gafas».")
add(R,"la pijama","Ropa para dormir.","Todavía estaba en pijama a mediodía.",["el pijama"],"En México se dice «la pijama»; en España, «el pijama».")
add(R,"el saco","Prenda formal con mangas que se lleva sobre la camisa.","Se puso saco y corbata para la boda.",["la americana","la chaqueta"],"En México: «saco»; en España: «americana».")
add(R,"el mandil","Prenda que protege la ropa cuando cocinas.","Se puso el mandil para cocinar.",["el delantal"],"En México: «mandil»; en España: «delantal».")
add(R,"la falda","Prenda de mujer que cuelga de la cintura.","Llevaba una falda larga de lana.")
add(R,"las botas","Calzado alto que cubre el tobillo.","Se le mojaron las botas en el pantano.")
O = "objetos"
add(O,"el encendedor","Pequeño aparato para hacer fuego.","¿Tienes un encendedor para la vela?",["el mechero"],"En México: «encendedor»; en España también «mechero».")
add(O,"el foco","Objeto de cristal que da luz eléctrica.","Se fundió el foco de la cocina.",["la bombilla"],"En México: «foco»; en España: «bombilla».")
add(O,"la cobija","Tela gruesa para taparse en la cama.","Tráeme otra cobija, tengo frío.",["la manta"],"En México: «cobija»; en España: «manta».")
add(O,"la almohada","Objeto blando donde se apoya la cabeza para dormir.","Escondió la carta bajo la almohada.")
add(O,"el espejo","Cristal donde ves tu propia imagen.","Se miró en el espejo antes de salir.")
add(O,"las tijeras","Herramienta con dos hojas para cortar papel o tela.","Pásame las tijeras, por favor.")
add(O,"la escoba","Objeto para barrer el suelo.","Barrió el patio con la escoba.")
add(O,"el cerillo","Palito pequeño que se enciende al frotarlo.","Encendió la vela con un cerillo.",["la cerilla","el fósforo"],"En México: «cerillo»; en España: «cerilla».")
add(O,"la cubeta","Recipiente con asa para llevar agua.","Llenó la cubeta en el pozo.",["el cubo","el balde"],"En México: «cubeta»; en España: «cubo».")
add(O,"la pluma","Objeto con tinta para escribir.","Firmó el documento con una pluma.",["el bolígrafo","el boli"],"En México: «pluma»; en España: «bolígrafo».")
add(O,"la cartera","Objeto pequeño donde se guarda el dinero.","Perdió la cartera en el mercado.")
add(O,"el paraguas","Objeto para protegerse de la lluvia.","Abre el paraguas, está lloviendo.")
add(O,"la vela","Cilindro de cera que da luz al quemarse.","Leía a la luz de una vela.")
add(O,"el clavo","Pieza de metal delgada que se mete con un martillo.","Colgó el cuadro de un clavo.")
add(O,"el martillo","Herramienta para golpear clavos.","Necesito el martillo para arreglar la mesa.")
add(O,"la cuerda","Hilos gruesos torcidos para atar cosas.","Ataron la caja con una cuerda.")
add(O,"la llave","Pieza de metal que abre una cerradura.","¿Dónde dejaste la llave del archivo?")
add(O,"el candado","Cerradura que se cuelga para cerrar una puerta o una caja.","El cofre tenía un candado oxidado.")
E = "emociones"
add(E,"la vergüenza","Lo que sientes cuando haces algo ridículo delante de otros.","Se puso rojo de vergüenza.",["la pena"],"En México también se dice «me da pena» por «me da vergüenza».")
add(E,"el orgullo","Satisfacción por algo que has logrado.","Habló de su hija con orgullo.")
add(E,"la envidia","Deseo de tener lo que tiene otra persona.","Le tenía envidia por su éxito.")
add(E,"los celos","Miedo a que la persona que quieres prefiera a otra.","Los celos arruinaron su amistad.")
add(E,"el alivio","Lo que sientes cuando termina una preocupación.","Fue un alivio saber que estaba vivo.")
add(E,"la nostalgia","Tristeza por recordar el pasado o un lugar lejano.","Sintió nostalgia de su pueblo.")
add(E,"la culpa","Sentimiento de haber hecho algo malo.","No podía dormir por la culpa.")
add(E,"el asco","Rechazo fuerte ante algo sucio o desagradable.","El olor del pantano le dio asco.")
add(E,"la angustia","Miedo intenso y sin causa clara que aprieta el pecho.","Esperaba la noticia con angustia.")
add(E,"la ternura","Cariño suave, como el que se siente por un niño.","Miró al bebé con ternura.")
add(E,"el rencor","Enojo que guardas mucho tiempo contra alguien.","No le guardo rencor.")
add(E,"la gratitud","Sentimiento de querer devolver un favor.","Le escribió una carta de gratitud.")
add(E,"la soledad","Estado de quien se siente solo.","La soledad del archivo le pesaba.")
add(E,"el entusiasmo","Energía alegre por hacer algo.","Empezó el proyecto con entusiasmo.")
add(E,"el coraje","En México: enojo fuerte.","Le dio mucho coraje que le mintieran.",["el enojo","la rabia"],"En México «coraje» suele significar enojo; en España, valentía.")
add(E,"la desconfianza","Falta de confianza; sospecha.","Lo miró con desconfianza.")
K = "cocina"
add(K,"la olla","Recipiente hondo para hervir o cocinar guisos.","Puso los frijoles en la olla.")
add(K,"el sartén","Recipiente plano con mango para freír.","Calienta el aceite en el sartén.",["la sartén"],"En México se dice «el sartén»; en España, «la sartén».")
add(K,"el cucharón","Cuchara grande para servir sopa.","Sirvió el pozole con el cucharón.")
add(K,"el tenedor","Cubierto con puntas para pinchar la comida.","Comía la ensalada con tenedor.")
add(K,"el cuchillo","Cubierto con hoja para cortar.","Corta la cebolla con este cuchillo.")
add(K,"la licuadora","Aparato eléctrico para hacer jugos y salsas.","Prepara la salsa en la licuadora.",["la batidora"],"En México: «licuadora»; en España: «batidora» o «licuadora».")
add(K,"la estufa","Aparato con fuegos para cocinar.","Deja la olla en la estufa.",["la cocina","los fogones"],"En México: «estufa»; en España: «cocina».")
add(K,"el refrigerador","Aparato que mantiene fría la comida.","Guarda la leche en el refrigerador.",["el refri","la nevera","el frigorífico"],"En México: «refrigerador» o «refri»; en España: «nevera».")
add(K,"el comal","Disco de barro o metal para calentar tortillas.","Calentó las tortillas en el comal.")
add(K,"el molcajete","Mortero de piedra volcánica para moler chiles y hacer salsa.","Hizo la salsa en el molcajete.")
add(K,"el horno","Aparato cerrado para cocinar pan o carne con calor.","El pan está en el horno.")
add(K,"la tabla de picar","Pieza de madera donde se cortan los alimentos.","Pica el cilantro en la tabla de picar.")
add(K,"el colador","Utensilio con agujeros para separar el líquido.","Pasa la pasta por el colador.")
add(K,"el rallador","Utensilio para rallar queso o zanahoria.","Usa el rallador para el queso.")
add(K,"la jarra","Recipiente con asa para servir agua.","Trajo una jarra de agua de jamaica.")
add(K,"el abrelatas","Utensilio para abrir latas.","No encuentro el abrelatas.")
add(K,"la tapa","Lo que cierra una olla por arriba.","Ponle la tapa a la olla.")
A = "conceptos"
add(A,"la justicia","Dar a cada persona lo que le corresponde según la ley o la razón.","El pueblo pedía justicia por la muerte de Tomás.")
add(A,"la libertad","Poder decidir y actuar sin estar preso ni obligado.","Lucharon por la libertad de imprenta.")
add(A,"la verdad","Lo que corresponde a los hechos reales.","Nadie quería decir la verdad.")
add(A,"la confianza","Seguridad de que alguien no te va a fallar.","Perdió la confianza del abad.")
add(A,"la lealtad","Fidelidad a una persona, idea o grupo.","Su lealtad al obispo era total.")
add(A,"la venganza","Daño que haces a alguien porque antes te hizo daño.","No buscaba venganza, sino respuestas.")
add(A,"el perdón","Dejar de culpar a alguien por lo que hizo.","Le pidió perdón a su hermano.")
add(A,"la responsabilidad","Obligación de responder por lo que haces.","Asumió la responsabilidad del error.")
add(A,"la igualdad","Que todas las personas tengan los mismos derechos.","Defendía la igualdad ante la ley.")
add(A,"el poder","Capacidad de mandar o de controlar a otros.","El poder del tribunal era enorme.")
add(A,"la memoria","Capacidad de recordar; también lo que una comunidad recuerda.","La memoria del pueblo guarda los nombres.")
add(A,"la esperanza","Creer que algo bueno va a pasar.","Todavía tenía esperanza de encontrarlo.")
add(A,"la duda","No estar seguro de algo.","Tengo una duda sobre la fecha.")
add(A,"la sabiduría","Conocimiento profundo que da la experiencia.","La sabiduría del médico salvó vidas.")
add(A,"la dignidad","Valor que merece toda persona y que exige respeto.","Lo trataron sin dignidad.")
add(A,"la corrupción","Usar un cargo público para beneficio propio.","La corrupción llegó hasta el archivo.")
add(A,"la amenaza","Aviso de que alguien te va a hacer daño.","Recibió una amenaza anónima.")
add(A,"la promesa","Compromiso de hacer algo en el futuro.","Cumplió su promesa al final.")
add(A,"la sospecha","Idea de que algo malo pasa, sin pruebas completas.","Tenía la sospecha de que el vino estaba alterado.")
add(A,"la prueba","Lo que demuestra que algo es verdad.","Sin pruebas no hay acusación.")
# Connectors: cloze sentences; answer in the blank, meaning clue in Spanish.
L = []
def link(answer, meaning, sentence, alt=None, note=""):
    L.append({"word": answer, "clue": meaning + " · " + sentence, "example": sentence.replace("___", answer), "alt": alt or [], "note": note, "cloze": True})
link("sin embargo","Contraste («pero», con más peso)","El abad parecía amable; ___, ocultaba algo.",["no obstante"],"«No obstante» es más formal.")
link("no obstante","Contraste formal, de documentos","La orden es válida; ___, no trae pruebas médicas.",["sin embargo"])
link("mientras tanto","Al mismo tiempo, en otro lugar","Mateo revisaba el archivo; ___, Inés vigilaba el puerto.",["entretanto"],"«Entretanto» es más literario.")
link("aunque","Concesión: algo no impide lo otro","Fue al monasterio ___ estaba lloviendo.",["a pesar de que"])
link("a pesar de que","Concesión, más enfática que «aunque»","___ tenía miedo, entró en la cripta.",["aunque"])
link("así que","Consecuencia, en la conversación","No había pan en la venta, ___ seguimos sin comer.",["entonces","por eso","por lo tanto"])
link("por lo tanto","Consecuencia, en un razonamiento","El sello es falso; ___, la orden no es válida.",["así que","por eso","en consecuencia"])
link("entonces","Consecuencia o paso siguiente","¿No viste a nadie? ___, ¿quién abrió la puerta?",["así que"])
link("por eso","Causa ya dicha → consecuencia","Estaba enfermo; ___ no vino al consejo.",["así que","por lo tanto"])
link("o sea","Aclaración, muy común en México","Llegó tarde, ___, después de la medianoche.",["es decir"])
link("es decir","Aclaración formal","El documento es un palimpsesto, ___, tiene texto debajo.",["o sea"])
link("de hecho","Confirma o refuerza con un dato","No es un rumor; ___, lo vi con mis propios ojos.",["en realidad"])
link("en cambio","Contraste entre dos personas o cosas","Lucio habla poco; Gabriel, ___, no se calla.",["por el contrario"])
link("además","Añade información","El vino estaba alterado; ___, faltaba un cuaderno.",["también"])
link("por cierto","Introduce un tema nuevo de pasada","___, ¿sabes dónde está Elías?")
link("en fin","Resume o cierra la conversación","Discutimos dos horas; ___, mañana lo decidimos.")
link("sin duda","Seguridad total","Es, ___, la letra de Tomás.",["sin lugar a dudas"])
link("aun así","Contraste: a pesar de lo dicho","Le advirtieron del peligro; ___, cruzó el puente.",["sin embargo"])
T["conectores"] = L
NAMES = {"cuerpo": "Partes del cuerpo", "ropa": "Ropa", "objetos": "Objetos de casa", "emociones": "Emociones",
	"cocina": "Utensilios de cocina", "conceptos": "Conceptos abstractos", "conectores": "Conectores del discurso"}
out = {"version": 1, "variety": "es-MX primero; la variante de España se acepta con una nota", "level": "B1",
	"themes": []}
for key in ["cuerpo","ropa","objetos","emociones","cocina","conceptos","conectores"]:
	items = []
	for n, entry in enumerate(T[key], 1):
		e = dict(entry); e["id"] = "%s_%02d" % (key, n)
		items.append(e)
	out["themes"].append({"id": key, "name": NAMES[key], "items": items})
json.dump(out, open("game/content/spanish/vocabulary.json","w"), ensure_ascii=False, indent=2)
print(sum(len(t["items"]) for t in out["themes"]))
